{
  "openapi": "3.0.3",
  "info": {
    "title": "Second Hand",
    "description": "OpenAPI for Second Hand",
    "version": "1",
    "contact": {
      "name": "FSW13 Team 3"
    },
    "license": {
      "name": "APACHE 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0"
    }
  },
  "tags": [
    {
      "name": "Users",
      "description": "API for users in the system"
    },
    {
      "name": "Product",
      "description": "API for product in the system"
    },
    {
      "name": "Offer",
      "description": "API for offer in the system"
    },
    {
      "name": "Sale",
      "description": "API for sale in the system"
    }
  ],
  "servers": [
    {
      "description": "Product Management API Server",
      "url": "http://localhost:3000/{env}",
      "variables": {
        "env": {
          "description": "Server Environment",
          "default": "api/v1",
          "enum": [
            "api/v1",
            "dev"
          ]
        }
      }
    }
  ],
  "externalDocs": {
    "url": "https://swagger.io/docs/specification/about/",
    "description": "OpenAPI Guide"
  },
  "paths": {
    "/register": {
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Create new user",
        "description": "Create new user",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success creating new user"
          }
        }
      }
    },
    "/login": {
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Login user",
        "description": "Login user",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "superadmin": {
                  "description": "login as superadmin",
                  "value": {
                    "email": "admin@gmail.com",
                    "password": "password"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Login Success"
          }
        }
      }
    },
    "/user/{id}": {
      "put": {
        "security": [{
          "ProductAuth": []
        }],
        "tags": [
          "Users"
        ],
        "summary": "Update Data User",
        "description": "Update data user",
        "parameters": [
          {
            "$ref": "#/components/parameters/id"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProductSchemaReqBody"
              },
              "examples": {
                "dummy_input": {
                  "description": "Example Data User",
                  "value": {
                    "name": "admin",
                    "email": "admin@gmail.com",
                    "password": "123456",
                    "no_tlpn": "081234567890",
                    "city": "Surabaya",
                    "address": "Surabaya",
                    "image": "image",
                    "createdAt": "2022-05-10T17:02:45.225Z",
                    "updatedAt": "2022-05-10T17:02:45.225Z"
                  }
                }
              }
            }
          }
        },
        "responses": {}
      }
    },
    "/product": {
      "get": {
        "security": [],
        "tags": [
          "Product"
        ],
        "summary": "Get All Product",
        "description": "Get all product in system",
        "responses": {
          "200": {
            "description": "Success get all products",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer"
                      },
                      "id_user": {
                        "type": "integer"
                      },
                      "product_name": {
                        "type": "string"
                      },
                      "product_price": {
                        "type": "integer"
                      },
                      "category": {
                        "type": "string"
                      },
                      "description": {
                        "type": "string"
                      },
                      "image": {
                        "type": "string"
                      },
                      "status": {
                        "type": "string"
                      }
                    }
                  }
                },
                "examples": {
                  "success": {
                    "description": "Example success get all product",
                    "value": [
                      {
                        "id": 1,
                        "id_user": 1,
                        "product_name": "Jam Tangan Casio",
                        "product_price": 250000,
                        "category": "Aksesoris",
                        "description": "Hitam",
                        "image": "./images/min.jpg",
                        "status": "available"
                      },
                      {
                        "id": 2,
                        "id_user": 2,
                        "product_name": "Jam Tangan Casio X",
                        "product_price": 280000,
                        "category": "Aksesoris",
                        "description": "Putih",
                        "image": "./images/min.jpg",
                        "status": "available"
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "ProductAuth": []
          }
        ],
        "tags": [
          "Product"
        ],
        "summary": "Create New Product",
        "description": "Create a product",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProductSchemaReqBody"
              },
              "examples": {
                "products": {
                  "value": {
                    "product_name": "Jam Tangan Casio Y",
                    "product_price": 280000,
                    "category": "Aksesoris",
                    "description": "Putih",
                    "image": "./images/min.jpg",
                    "status": "available"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Succes create new product",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/product/{id}": {
      "put": {
        "security": [
          {
            "ProductAuth": []
          }
        ],
        "tags": [
          "Product"
        ],
        "summary": "Update Data Product",
        "description": "Update data product",
        "parameters": [
          {
            "$ref": "#/components/parameters/id"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProductSchemaReqBody"
              },
              "examples": {
                "dummy_input": {
                  "description": "Example Data Product",
                  "value": {
                    "product_name": "Jam Tangan Casio Y",
                    "product_price": 280000,
                    "category": "Aksesoris",
                    "description": "Putih",
                    "image": "./images/min.jpg",
                    "status": "available",
                    "createdAt": "2022-05-10T17:02:45.225Z",
                    "updatedAt": "2022-05-10T17:02:45.225Z"
                  }
                }
              }
            }
          }
        },
        "responses": {}
      }
    },
    "/offer": {
      "get": {
        "security": [
          {
            "ProductAuth": []
          }
        ],
        "tags": [
          "Offer"
        ],
        "summary": "Get All Offer",
        "description": "Get all offer in system",
        "responses": {
          "200": {
            "description": "Success get all offer",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer"
                      },
                      "id_user": {
                        "type": "integer"
                      },
                      "id_product": {
                        "type": "integer"
                      },
                      "product_name": {
                        "type": "string"
                      },
                      "bid_price": {
                        "type": "integer"
                      }
                    }
                  }
                },
                "examples": {
                  "success": {
                    "description": "Example success get all offer",
                    "value": [
                      {
                        "id": 1,
                        "id_user": 1,
                        "id_product": 1,
                        "product_name": "Jam Tangan Casio",
                        "bid_price": 190000
                      },
                      {
                        "id": 2,
                        "id_user": 3,
                        "id_product": 1,
                        "product_name": "Jam Tangan Casio",
                        "bid_price": 180000
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "ProductAuth": []
          }
        ],
        "tags": [
          "Offer"
        ],
        "summary": "Create New Offer",
        "description": "Create a offer",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/OfferSchemaReqBody"
              },
              "examples": {
                "products": {
                  "value": {
                    "id_product": 1,
                    "bid_price": 180000
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Succes create new offer",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/sale": {
      "get": {
        "security": [
          
        ],
        "tags": [
          "Sale"
        ],
        "summary": "Get All Sale",
        "description": "Get all sale in system",
        "responses": {
          "200": {
            "description": "Success get all sale",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer"
                      },
                      "id_product": {
                        "type": "integer"
                      },
                      "id_offer": {
                        "type": "integer"
                      }
                    }
                  }
                },
                "examples": {
                  "success": {
                    "description": "Example success get all sale",
                    "value": [
                      {
                        "id": 1,
                        "id_product": 1,
                        "id_offer": 1
                      },
                      {
                        "id": 2,
                        "id_product": 2,
                        "id_offer": 2
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "security": [
          
        ],
        "tags": [
          "Sale"
        ],
        "summary": "Create New Sale",
        "description": "Create a sale",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SaleSchemaReqBody"
              },
              "examples": {
                "products": {
                  "value": {
                    "id_product": 1,
                    "id_offer": 1
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Succes create new sale",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "ProductAuth": {
        "description": "Authentication for Second Hand Management API",
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "parameters": {
      "id": {
        "name": "id",
        "in": "path",
        "required": true,
        "description": "Product id for spesific product",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 100
        }
      }
    },
    "schemas": {
      "ProductSchemaReqBody": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "product_name": {
            "type": "string"
          },
          "product_price": {
            "type": "integer"
          },
          "category": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "image": {
            "type": "string"
          },
          "status": {
            "type": "string"
          }
        }
      },
      "OfferSchemaReqBody": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "id_product": {
            "type": "integer"
          },
          "bid_price": {
            "type": "integer"
          }
        }
      },
      "SaleSchemaReqBody": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "id_product": {
            "type": "integer"
          },
          "id_offer": {
            "type": "integer"
          }
        }
      }
    }
  }
}